spring:
  docker:
    compose:
      file: src/main/docker/compose.yaml
      lifecycle-management: start_only
      enabled: true

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

server:
  port: 8081

jwt:
  secret:
    key: k3qPf+6b3vQZ7uQ9Tg9z9LzQ7cBx7v5t3b1T9H7uJ3A=
