spring:

  docker:
    compose:
      file: src/main/docker/compose.yaml
      lifecycle-management: start_only
      enabled: true

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

server:
  port: 8081