name: hunters_league
services:
  postgres:
    container_name: hunters_league
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=hunters_league'
      - 'POSTGRES_PASSWORD=hunters_league'
      - 'POSTGRES_USER=hunters_league'
    ports:
      - '5433:5432'
volumes:
  postgres_data:
    driver: local